# Creation date : 22.08.2022
# Created by : CSR
# Description : Create two containers (one for the db and the other one of the administration front-end)
# 
services:
  db:
    image: mysql:8.0.30
    container_name: db_flashcards
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: db_flashcards
    restart: always
    ports:
      - "6033:3306"
    networks:
      - flashcards_network
    volumes:
      - dbdata:/var/lib/mysql
      - ./scripts:/scripts
  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: pma_flashcards
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - flashcards_network
  adonis:
    container_name: adonis_flashcards
    build:
      context: .
      dockerfile: adonis.dockerfile
    restart: always
    ports:
      - 3333:3333
    networks:
      - flashcards_network
    environment:
      - HOST=0.0.0.0
      - PORT=3333
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=db_flashcards
    depends_on:
      - db

# The database will be persistent among containers restarts.
volumes:
  dbdata:

networks:
  flashcards_network:
    driver: bridge

